openapi: 3.0.0
info:
  title: Planetary API
  description: API to get planetary positions, power scores, and other astrological information based on date, time, latitude, and longitude.
  version: 1.0.0
servers:
  - url:  https://087a-209-222-126-192.ngrok-free.app
    description: Local server
paths:
  /planets/natal-planets:
    get:
      operationId: getNatalPlanets
      summary: Get planetary positions
      description: Returns the positions of planets based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of planetary positions
          content:
            application/json:
              schema:
                type: object
                properties:
                  planets:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/power-scores:
    get:
      operationId: getPowerScores
      summary: Get planetary power scores
      description: Returns the total power scores of planets based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of planetary power scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/southNode:
    get:
      operationId: getSouthNode
      summary: Get South Node Configuration
      description: Returns the South Node configuration based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: South Node Configuration
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/sign-scores:
    get:
      operationId: getSignScores
      summary: Get Sign Scores
      description: Returns the sign scores based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of sign scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/house-scores:
    get:
      operationId: getHouseScores
      summary: Get House Scores
      description: Returns the house scores based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of house scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/house-harmony:
    get:
      operationId: getHouseHarmony
      summary: Get House Harmony Scores
      description: Returns the house harmony scores based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of house harmony scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/sign-harmony:
    get:
      operationId: getSignHarmony
      summary: Get Sign Harmony Scores
      description: Returns the sign harmony scores based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of sign harmony scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/planet-harmony:
    get:
      operationId: getPlanetHarmony
      summary: Get Planet Harmony Scores
      description: Returns the planet harmony scores based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of planet harmony scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
  /planets/natal-aspects:
    get:
      operationId: getNatalAspects
      summary: Get Natal Aspects
      description: Returns the natal aspects based on the provided date, time, latitude, and longitude.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
          description: Date in ISO 8601 format (YYYY-MM-DD).
        - name: time
          in: query
          required: true
          schema:
            type: string
            format: time
          description: Time in ISO 8601 format (HH:MM:SS).
        - name: lat
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Latitude of the location.
        - name: lon
          in: query
          required: true
          schema:
            type: number
            format: float
          description: Longitude of the location.
      responses:
        '200':
          description: A list of natal aspects
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request, e.g., missing or invalid parameters
        '500':
          description: Internal Server Error
components:
  schemas:
    PlanetaryPositionsResponse:
      type: object
      properties:
        planets:
          type: array
          items:
            type: string
    PowerScoresResponse:
      type: object
      properties:
        scores:
          type: array
          items:
            type: string
    SouthNodeResponse:
      type: object
      properties:
        config:
          type: string
