openapi: 3.0.0
info:
  title: AstrologicAPI
  description: API to get planetary positions, power scores, south node configurations, and harmony scores based on a given date, time, latitude, and longitude.
  version: 1.0.0
servers:
  - url: https://ef1c-209-222-126-192.ngrok-free.app
    description: Development server
paths:
  /planets:
    get:
      summary: Get planetary positions
      operationId: getPlanets
      tags:
        - planets
      parameters:
        - name: date
          in: query
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            format: date
        - name: time
          in: query
          description: Time in HH:MM:SS format.
          required: true
          schema:
            type: string
            format: time
        - name: lat
          in: query
          description: Latitude.
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: Longitude.
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: A list of planetary positions
          content:
            application/json:
              schema:
                type: object
                properties:
                  planets:
                    type: array
                    items:
                      type: string
                    description: List of planetary positions
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /planets/power-scores:
    get:
      summary: Get power scores for planets
      operationId: getPowerScores
      tags:
        - planets
      parameters:
        - name: date
          in: query
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            format: date
        - name: time
          in: query
          description: Time in HH:MM:SS format.
          required: true
          schema:
            type: string
            format: time
        - name: lat
          in: query
          description: Latitude.
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: Longitude.
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: A list of power scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
                    description: List of power scores
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /planets/southNode:
    get:
      summary: Get south node configuration
      operationId: getSouthNode
      tags:
        - planets
      parameters:
        - name: date
          in: query
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            format: date
        - name: time
          in: query
          description: Time in HH:MM:SS format.
          required: true
          schema:
            type: string
            format: time
        - name: lat
          in: query
          description: Latitude.
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: Longitude.
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: A south node configuration
          content:
            application/json:
              schema:
                type: object
                properties:
                  config:
                    type: string
                    description: South node configuration details
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /planets/house-scores:
    get:
      summary: Get house scores for planets
      operationId: getHouseScores
      tags:
        - planets
      parameters:
        - name: date
          in: query
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            format: date
        - name: time
          in: query
          description: Time in HH:MM:SS format.
          required: true
          schema:
            type: string
            format: time
        - name: lat
          in: query
          description: Latitude.
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: Longitude.
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: A list of house scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
                    description: List of house scores
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /planets/sign-scores:
    get:
      summary: Get sign scores for planets
      operationId: getSignScores
      tags:
        - planets
      parameters:
        - name: date
          in: query
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            format: date
        - name: time
          in: query
          description: Time in HH:MM:SS format.
          required: true
          schema:
            type: string
            format: time
        - name: lat
          in: query
          description: Latitude.
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: Longitude.
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: A list of sign scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
                    description: List of sign scores
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /planets/planet-harmony:
    get:
      summary: Get planet harmony scores
      operationId: getPlanetHarmonyScores
      tags:
        - planets
      parameters:
        - name: date
          in: query
          description: Date in YYYY-MM-DD format.
          required: true
          schema:
            type: string
            format: date
        - name: time
          in: query
          description: Time in HH:MM:SS format.
          required: true
          schema:
            type: string
            format: time
        - name: lat
          in: query
          description: Latitude.
          required: true
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: Longitude.
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: A list of planet harmony scores
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: array
                    items:
                      type: string
                    description: List of planet harmony scores
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    PlanetaryPositionsResponse:
      type: object
      properties:
        planets:
          type: array
          items:
            type: string
    PowerScoresResponse:
      type: object
      properties:
        scores:
          type: array
          items:
            type: string
    SouthNodeResponse:
      type: object
      properties:
        config:
          type: string
